### PR TITLE
RDISCROWD-5307 Disable image uploads in task guidelines

### PR DESCRIPTION
**Pull request by kbecker42**
- Disable image upload from task guidelines widget (keep ability to link images).
- Cleanup UI borders for modals.

### After

Note, button for "Upload" is no longer displayed. Border spacing has been cleaned up.

after-1

after-2

### Before

Note, button for uploading files. Incorrect border spacing.

before

### CODE REVIEW

**Comment by XiChenn** [comment]
Will the CSS solution too easy to be hacked? Wonder if we could just remove it from UI if we want to disable the uploading from the local.
If we want to keep this feature, we can upload it to the same object store we used for user's avatar.

**Comment by kbecker42** [comment]
I'd hope that malicious user behavior wouldn't be the chief concern, provided the UI is hidden, it should not be used. The CSS approach also seems to be the most reasonable solution as noted [here|https://stackoverflow.com/a/33659947/2596404].

**Comment by XiChenn** [comment]
> I'd hope that malicious user behavior wouldn't be the chief concern, provided the UI is hidden, it should not be used. The CSS approach also seems to be the most reasonable solution as noted [here](https://stackoverflow.com/a/33659947/2596404).

**Review by XiChenn — APPROVED** [review]
lgtm, thank you.

**Pull request merged**
