### PR TITLE
RDISCROWD-1694 UI updates for Github and project sync details

### PR DESCRIPTION
**Pull request by primaryobjects**
- Fixed spacing of github and project sync details.
- Updated style for panels.
- Added collapsible control.

Ref https://github.com/bloomberg/pybossa/pull/281

## Screenshot: Responsive Collapse

github-push

## Screenshot: Style

github-push-message

### CODE REVIEW

**Comment by mariarivera30** [comment]
Can you please create a branch at the Pybossa pointing to this themes, I don't think this change can break anything but will be good to start doing that before we merge? It looks good!

**Comment by primaryobjects** [comment]
> Can you please create a branch at the Pybossa pointing to this themes

I have this open PR https://github.com/bloomberg/pybossa/pull/281 for the same ticket. Is there anything else to do for it?

**Comment by mariarivera30** [comment]
I missed that branch, but still it is not pointing to this commit. You need to add  themes/default into the other branch to point into this commit.

**Comment by primaryobjects** [comment]
> You need to add themes/default into the other branch to point into this commit.

Ok, the merge is [here](https://github.com/bloomberg/pybossa/pull/281/files#diff-55bafbecada9bdcfd2ab33f0148831d8).

**Pull request merged**
